# Generated by Django 3.2.6 on 2021-08-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('sensor', 'Sensor'), ('relay', 'Relay')], max_length=6)),
                ('gpio', models.IntegerField(blank=True)),
                ('sensor_type', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('devices', models.ManyToManyField(blank=True, to='devices.Device')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
