# Generated by Django 3.2.6 on 2021-08-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20210810_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='firmware',
            field=models.CharField(choices=[('tasmota', 'Tasmota'), ('simulated', 'Simulated')], default='tasmota', max_length=20),
        ),
    ]
