# Generated by Django 3.2.6 on 2021-08-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_firmware'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_host_id',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
