# Generated by Django 3.2.6 on 2021-08-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_device_host_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
