# Generated by Django 3.2.6 on 2021-08-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20210812_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devices.workspace'),
        ),
    ]
