# Generated by Django 3.2.6 on 2021-08-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_eventhubmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhubmsg',
            name='properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
