# Generated by Django 3.2.6 on 2021-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_eventhubmsg_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensor_type',
            field=models.CharField(blank=True, choices=[('---', None), ('am2301', 'AM2301')], default=None, max_length=10, null=True),
        ),
    ]
