# Generated by Django 3.2.6 on 2021-08-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_device_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensor_type',
            field=models.CharField(blank=True, choices=[(None, '---'), ('am2301', 'AM2301')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='workspace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='devices.workspace'),
        ),
    ]
