# Generated by Django 3.2.6 on 2021-08-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_auto_20210820_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='workspace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.workspace'),
        ),
    ]
