# Generated by Django 3.2.6 on 2021-08-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_auto_20210820_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceevent',
            options={'ordering': ['name']},
        ),
    ]
