# Generated by Django 3.2.6 on 2021-08-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_alter_deviceevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='reading_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='rule',
            field=models.CharField(blank=True, choices=[('=', '='), ('>', '>'), ('>=', '>='), ('<=', '<='), ('<', '<')], max_length=3, null=True),
        ),
    ]
