# Generated by Django 3.2.6 on 2021-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_auto_20210820_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='firmware',
            field=models.CharField(choices=[('tasmota', 'Tasmota')], default='tasmota', max_length=20),
        ),
    ]
