# Generated by Django 3.2.6 on 2021-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_alter_device_firmware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='rule',
            field=models.CharField(blank=True, choices=[('>', '>'), ('<', '<')], max_length=3, null=True),
        ),
    ]
