# Generated by Django 3.2.6 on 2021-09-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_alter_deviceevent_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='rule',
            field=models.CharField(blank=True, choices=[('>', 'is greater than'), ('<', 'is lower than')], max_length=3, null=True),
        ),
    ]
